version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
  # webpacker:
  #   build: .
  #   command: bundle exec bin/webpack-dev-server
  #   volumes:
  #     - .:/myapp
  #   ports:
  #     - '8080:8080'
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - RESTAURAMT_URL=$RESTAURANT_URL
      - RESTAURAMT_API=$RESTAURANT_API
    volumes:
      - .:/myapp
    tty: true
    stdin_open: true
    depends_on:
      - db
      # - webpacker
    links:
      - db
    ports:
      - '3000:3000'
